language: php

php:
    - "7.4"
    #- "8.0"

before_script:
    #- make install check
    - make install

before_script:
  - cp .env.travis .env
  - php artisan key:generate

script:
    - make test
