<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Http\Controllers\Game21Controller;
use App\Models\Game21\Game21;

class Game21ControllerTest extends TestCase
{
    /**
     * Test that the get-route /game21 renders an OK HTTP response (200),
     * and that the response contains part of the expected title string passed.
     *
     * @return void
     */
    public function testGetGame21Route()
    {
        $response = $this->get('/game21');

        $response->assertStatus(200);
        $response->assertSee('DiceLaVerdad');
    }

    /**
     * Test that the post-route /game21 renders an OK HTTP response (200),
     * and that the response contains a string generated by the Game21 class
     *
     * @return void
     */
    public function testPostGame21InitiateRoute()
    {

        $response = $this->withHeaders([
            'X-Header' => 'Value',
        ])->post('/game21initiate', [
            'oneortwo' => '1',
            'startgame' => 'Start!']);

        $response->assertStatus(200);
        $response->assertSee('Roll your dice again, or stop - your choice!');
    }

    /**
     * Test that the post-route /game21 renders an OK HTTP response (200),
     * and that the response contains a string generated by the Game21 class
     *
     * @return void
     */
    public function testPostGame21Route()
    {

        $game21Object = new Game21(1);
        session()->put('game21', $game21Object);

        $response = $this->withHeaders([
            'X-Header' => 'Value',
        ])->post('/game21', ['rollagain' => 'Roll again']);

        $response->assertStatus(200);
        $response->assertSee('Roll your dice again, or stop - your choice!');
    }

    /**
     * Test that object is instance of Game21Controller
     */
    public function testCreateTheControllerClass()
    {
        $controller = new Game21Controller();

        $this->assertInstanceOf("App\Http\Controllers\Game21Controller", $controller);
    }

    /**
     * Check that Game21Controller class extends Controller
     */
    public function testGame21ExtendsController()
    {
        $controller = new Game21Controller();

        $this->assertInstanceOf("App\Http\Controllers\Controller", $controller);
    }

}
